# Generated by Django 2.2.2 on 2020-06-19 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoatingLayer',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoatingOperator',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinalInspectionQualityControl',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.TextField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, default='', max_length=200)),
                ('qr_code', models.CharField(blank=True, default='', max_length=200)),
                ('repair', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('description', models.ForeignKey(blank=True, default='', null=True,
                                                  on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='app.Description')),
            ],
        ),
        migrations.CreateModel(
            name='LeadEngineer',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, default='', null=True,
                                           on_delete=django.db.models.deletion.SET_NULL, related_name='lead_engineers', to='app.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('surface_cleanliness_image', models.FileField(
                    blank=True, null=True, upload_to='surface_cleanliness/')),
                ('item', models.ForeignKey(blank=True, default='', null=True,
                                           on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='app.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('lead_engineer_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VulcanizationStep',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('lead_engineer', models.ForeignKey(blank=True, default='', null=True,
                                                    on_delete=django.db.models.deletion.SET_NULL, related_name='vulcanization_steps', to='app.LeadEngineer')),
            ],
        ),
        migrations.CreateModel(
            name='VulcanizationOperator',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('operator', models.ForeignKey(blank=True, default='', null=True,
                                               on_delete=django.db.models.deletion.SET_NULL, related_name='vulcanization_operators', to='app.Operator')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('lead', 'Lead Engineer'), ('supervisor', 'Supervisor'), (
                    'operator', 'Operator'), ('quality', 'Quality Control'), ('spectator', 'Spectator')], max_length=200)),
                ('name', models.CharField(default='', max_length=200, unique=True)),
                ('user', models.OneToOneField(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True,
                                          null=True, upload_to='document/')),
                ('file_description', models.CharField(
                    blank=True, default='', max_length=2000, null=True)),
                ('description', models.ForeignKey(blank=True, default='', null=True,
                                                  on_delete=django.db.models.deletion.SET_NULL, related_name='upload_files', to='app.Description')),
                ('final_inspection_quality_control', models.ForeignKey(blank=True, default='', null=True,
                                                                       on_delete=django.db.models.deletion.SET_NULL, related_name='upload_files', to='app.FinalInspectionQualityControl')),
                ('operator', models.ForeignKey(blank=True, default='', null=True,
                                               on_delete=django.db.models.deletion.SET_NULL, related_name='upload_files', to='app.Operator')),
            ],
        ),
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.CharField(blank=True, default='', max_length=200)),
                ('item', models.ForeignKey(blank=True, default='', null=True,
                                           on_delete=django.db.models.deletion.SET_NULL, related_name='seen', to='app.Item')),
            ],
        ),
        migrations.CreateModel(
            name='RubberCement',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('lead_engineer', models.ForeignKey(blank=True, default='', null=True,
                                                    on_delete=django.db.models.deletion.SET_NULL, related_name='rubber_cements', to='app.LeadEngineer')),
            ],
        ),
        migrations.CreateModel(
            name='PeelTestQualityControl',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('final_inspection_quality_control', models.ForeignKey(blank=True, default='', null=True,
                                                                       on_delete=django.db.models.deletion.SET_NULL, related_name='peel_test_quality_controls', to='app.FinalInspectionQualityControl')),
            ],
        ),
        migrations.CreateModel(
            name='MixDate',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('coating_operator', models.ForeignKey(blank=True, default='', null=True,
                                                       on_delete=django.db.models.deletion.SET_NULL, related_name='mix_dates', to='app.CoatingOperator')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementPointQualityControl',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('final_inspection_quality_control', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                                       related_name='measurement_point_quality_controls', to='app.FinalInspectionQualityControl')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementPointOperator',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('coating_operator', models.ForeignKey(blank=True, default='', null=True,
                                                       on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_point_operators', to='app.CoatingOperator')),
                ('vulcanization_operator', models.ForeignKey(blank=True, default='', null=True,
                                                             on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_point_operators', to='app.VulcanizationOperator')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementPointActualTVD',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('lead_engineer', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                    related_name='measurement_point_actual_tdvs', to='app.LeadEngineer')),
                ('operator', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='measurement_point_actual_tdvs', to='app.Operator')),
            ],
        ),
        migrations.CreateModel(
            name='HardnessQualityControl',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('final_inspection_quality_control', models.ForeignKey(blank=True, default='', null=True,
                                                                       on_delete=django.db.models.deletion.CASCADE, related_name='hardness_quality_controls', to='app.FinalInspectionQualityControl')),
            ],
        ),
        migrations.AddField(
            model_name='finalinspectionqualitycontrol',
            name='item',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='final_inspection_quality_controls', to='app.Item'),
        ),
        migrations.CreateModel(
            name='FinalInspectionDimensionsCheckQualityControl',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('final_inspection_quality_control', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                                       related_name='final_inspection_dimensions_check_quality_controls', to='app.FinalInspectionQualityControl')),
            ],
        ),
        migrations.CreateModel(
            name='FinalInspectionDimensionsCheck',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('lead_engineer', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                    related_name='final_inspection_dimensions_checks', to='app.LeadEngineer')),
            ],
        ),
        migrations.CreateModel(
            name='FinalInspectionCustomTestQualityControl',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('final_inspection_quality_control', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                                       related_name='final_inspection_custom_test_quality_controls', to='app.FinalInspectionQualityControl')),
            ],
        ),
        migrations.CreateModel(
            name='FinalInspectionCustomTest',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('lead_engineer', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                    related_name='final_inspection_custom_tests', to='app.LeadEngineer')),
            ],
        ),
        migrations.AddField(
            model_name='description',
            name='project',
            field=models.ForeignKey(blank=True, default='', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, related_name='descriptions', to='app.Project'),
        ),
        migrations.CreateModel(
            name='CumulativeThickness',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('coating_layer', models.ForeignKey(blank=True, default='', null=True,
                                                    on_delete=django.db.models.deletion.SET_NULL, related_name='cumulative_thickness', to='app.CoatingLayer')),
            ],
        ),
        migrations.AddField(
            model_name='coatingoperator',
            name='vulcanization_operator',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='coating_operators', to='app.VulcanizationOperator'),
        ),
        migrations.AddField(
            model_name='coatinglayer',
            name='vulcanization_step',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='coating_layers', to='app.VulcanizationStep'),
        ),
        migrations.CreateModel(
            name='AdditionalCustomTestOperator',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('operator', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='additional_custom_test_operators', to='app.Operator')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalCustomTest',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('lead_engineer', models.ForeignKey(blank=True, default='', null=True,
                                                    on_delete=django.db.models.deletion.SET_NULL, related_name='additional_custom_tests', to='app.LeadEngineer')),
            ],
        ),
    ]
