# Generated by Django 2.2.2 on 2020-07-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_layer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mixdate',
            name='coating_operator',
        ),
        migrations.CreateModel(
            name='RubberCementOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('operator', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubber_cement_operators', to='app.Operator')),
            ],
        ),
        migrations.AddField(
            model_name='mixdate',
            name='rubber_cement_operator',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mix_dates', to='app.RubberCementOperator'),
        ),
    ]
