# Generated by Django 2.2.2 on 2020-07-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200706_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='surface_cleanliness_image',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
    ]
